### ISSUE TITLE
[RFC] suggest & prioritize improvements to editing workflow

### ISSUE THREAD

**Issue by sjamesparsonsjr** [DIYbiosphere/sphere#256] opened 2019-10-16 15:46 UTC
Hi Jason, I started to upload logos and headers to Github via Master. However, there is no update to the  https://sphere.diybio.org/ website.

 I read in the Gitter you had similar problems back in May with the new hosting client netlify, and are using Staging to trigger the update via merge. I tried it with no success. 

On the netlify deploy status, it appears there hasn't been a successful deployment since June.  

 I'm probably missing something, please let me know.

**Comment by jasonbobe** [comment] 2019-10-16 16:43
Mac - James is updating DIYbiosphere. Any chance you can help him solve the
commit issue?

Jason

**Comment by 100ideas** [comment] 2019-10-18 11:03
I think the issue was a [syntax error in the yaml frontmatter of a file added june 14](https://github.com/DIYbiosphere/sphere/blame/6086baf632ec3722676574ea3e7c9c29e973df97/_startups/ConectorCiencia/ConectorCiencia.md#L12) (caused by a single extra whitespace). This was causing the yaml parser used by jekyll to crash and burn, [which unfortunately was killing the entire build process](https://app.netlify.com/sites/diybiosphere/deploys/5da9836aff4d48bd95fc8748).

I fixed the yaml error (#257) so we should know soon if it was the culprit - just need to netlify to trigger preview build for staging (for some reason it had stopped building staging previews, ...so also fixed that I think).

Lets use this thread to discuss / take notes on 

1) various ways of preventing this particular failure mode from happening again; and 

2) which approach to 1) would also help advance other desired upgrades / features (web-based editor perhaps? then we could validate yaml before committing it...)

**Comment by sjamesparsonsjr** [comment] 2019-10-18 12:02
Hi Mac, it's a pleasure to meet you.  It seems like the current bug was squashed. 

What etiquette do you want for site updating?  Staging -> Master?  Does it matter if I just use master for uploading pictures?

**Comment by 100ideas** [comment] 2019-10-18 12:03
There also seemed to be a problem with algolia api keys. the algolia-jekyll plugin couldn't talk to the algolia api and was returning an error at the end of the build process, which netlify interpreted as a build failure.

Two things we might need to do to make our build process more robust:

1) prevent algolia's indexer from returning an error to the algolia build process if it fails. But now that the api keys are fixed, maybe not a big deal.

2) protect against build failures caused by syntax errors or incorrect data types in yaml frontmatter (the latter type of error is harder to automatically detect because it requres understanding the semantics of the yaml fields, which are defined somewhere deep in our own code, probably not even in a single schema file, whereas the syntax of yaml is defined globally by the language definition itself. Basically it appears that the the jekyll yaml parser doesn't like it if someone puts the wrong kind of data in a yaml-field, such as `end-date: sometime` instead of `end-date: 2019-08-08`; "sometime" is a string that cannot be interpreted as a "date" as required in our app.)  that said, we could 

    a) add a hook somewhere or other (code review automation here on github maybe triggered on pull requests or commits?) that runs a yaml-linter to at least catch syntax errors, and/or

   b) extract or define the schema of allowed values for each possible property in the yaml-frontmatter (perhaps converting everything to json then using json-schema) so that we can also check for semantic mistakes, and/or 

   c) look into adding a web-based editor to both make it easier for users to create / edit new content, and also make it easier for us to build in our own validation logic. an editor could potentially use `isomorphic-git` in the browser to directly commit public edits to a `public` branch, which we would then manually review, for instance.

At the very very least, if the builds start failing again, keep your eye out for yaml mistakes as the culprit.

**Comment by 100ideas** [comment] 2019-10-18 12:03
after merging staging into masster, #255, production seems to be working properly now and serving the missing files.

**Comment by 100ideas** [comment] 2019-10-18 12:09
Oops, wanted to have a discussion here so no closing the thread!

@sjamesparsonsjr thanks for asking about the dev process. I would recommend making edits to the `staging` branch.  Netlify is now correctly building previews of all commits to all branches - after you commit or merge a PR, the netlify app decorates the issue / PR message with some status updates, including a link to the deploy preview if it builds. you just have to click the 'show details' button.

if the preview looks good, then merge staging into master

one last thing - since a lot of contributions happen via the github web editor on the `master` branch, it would be good to first merge `master -> staging` so its up to date.

**Comment by 100ideas** [comment] 2019-10-18 12:10
here's what the expanded netlify build message looks like

<img width="802" alt="Screen Shot 2019-10-18 at 5 05 14 AM" src="https://user-images.githubusercontent.com/57006/67092990-79dc9180-f165-11e9-8e9b-775982dfb0cd.png">

**Comment by 100ideas** [comment] 2019-10-18 12:13
@sjamesparsonsjr re just using master for uploading pictures... I think thats the convention around here so go ahead. 

That said if you happen to notice its been 10+ commits or a few months since staging was merged, feel free to merge them as discussed.

**Comment by sjamesparsonsjr** [comment] 2019-10-18 12:15
@100ideas sounds good

**Comment by sjamesparsonsjr** [comment] 2019-10-21 01:32
@100ideas Hi Mac, I've finished uploading all of the headers and logos for _startups. Before I start editing them I want to see the published version, however, the site is still crashing.  I get a build error `The tag `last_modified_at` on line 5 in `_includes/content.html` is not a recognized Liquid tag. For more information, see https://help.github.com/en/articles/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.`

**Comment by 100ideas** [comment] 2019-10-21 10:59
I wasn't able to replicate the error you mentioned above re `last_modified_at`. 

The build failures on netlify seem to have been caused by the `jekyll-algolia` plugin getting empty `_geoloc.lat` or `_geoloc.lng` fields on an entry (see [bottom of this build log](https://app.netlify.com/sites/diybiosphere/deploys/5dad8c8c28bed453904e5d30)).

```log
3:47:32 AM: [jekyll-algolia] Error:                                                          
3:47:32 AM: 400: Cannot POST to https://ITI5JHZJM9.algolia.net/1/indexes/*/batch:            
3:47:32 AM: {"message":"_geoloc.lat or _geoloc.lng attributes cannot be null near line:1     
3:47:32 AM: column:13786","status":400} (400)  
``` 

I think this file was the problem: 
- https://github.com/DIYbiosphere/sphere/blob/415dbedcca4b442a8f766c57878237954a23ec1d/_startups/CellEleven/CellEleven.md

I removed the empty fields and the build succeeded:
- https://github.com/DIYbiosphere/sphere/commit/120bc1abb2f068a6266c23c2075e0afe6a9d998e
- https://app.netlify.com/sites/diybiosphere/deploys/5dad8ddb4a152e00086db198

now lets see if merging `staging` to `master` results in a good build...

**Comment by 100ideas** [comment] 2019-10-21 11:10
I just mreged staging into master #272 and it seems to have worked.

https://app.netlify.com/sites/diybiosphere/deploys/5dad8fefc3371300081a40a1

so, going forward, just comment out any empty fields in the yml frontmatter.

**good**
```yml
#BASIC INFO
title: Cell Eleven
subtitle: Democratized Biotech
type-org: startup
#LOCATION
# address: # street and number
city: Philadelphia
state: Pennsylvania
postcode: 19135
country: United States
# _geoloc: # Geolocation coordinates for mapping
#  lat: # latitude number
#  lng: # longitude number
---
```

**bad**
```yml
---
#BASIC INFO
title: Cell Eleven
subtitle: Democratized Biotech
type-org: startup
#LOCATION
address: 
city: Philadelphia
state: Pennsylvania
postcode: 19135
country: United States
_geoloc: # Geolocation coordinates for mapping
  lat: # WARNING THIS IS BLANK AND WILL BREAK BUILD # latitude number
  lng: # WARNING THIS IS BLANK AND WILL BREAK BUILD # longitude number
---
```

**Comment by danwchan** [comment] 2021-03-06 22:21
Since this issue is already referenced in relevant open issues I will close this now

**Closed by danwchan** 2021-03-06 22:21 UTC
